server:
  port: 8080

spring:
  application:
    name: order-management-system

logging:
  level:
    root: INFO

grpc:
  server:
    port: 9090

order:
  scheduler:
    interval-ms: 300000  # 5 minutes in milliseconds (default)

